version: '3.8'

services:
  # Service Aplikasi Go Gateway
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-gateway-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

